kumuluzee:
  name: image-catalog-services
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql::database-1.cgjpznojjyw2.eu-central-1.rds.amazonaws.com:5432/image
      username: dbuser
      password: logitech123
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  configuration-properties:
    comments-service:
      enabled: true