kumuluzee:
  name: image-catalog-services
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql:database-1.cgjpznojjyw2.eu-central-1.rds.amazonaws.com:5432/image
      username: dbuser
      password: logitech123
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: api/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="4045afba-fee9-431d-b418-05d8b5f1150b-ls.logit.io"
                                  port="17055" protocol="tcp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info"/>
                                      <AppenderRef ref="logstash" level="trace"/>
                                  </Root>
                              </Loggers>
                          </Configuration>'
  configuration-properties:
    comments-service:
      enabled: true