kumuluzee:
  name: image-catalog-services
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://database-1.cgjpznojjyw2.eu-central-1.rds.amazonaws.com/image
      username: dbuser
      password: logitech123
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: api/images/*
  rest-client:
    registrations:
      - class: image-analysing-api
        url: http://localhost:8082/api
        read-timeout: 5000
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="image-catalog">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="84d5d097-018f-40e5-a315-e4a0af033ee9-ls.logit.io"
                                  port="17271" protocol="tcp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info"/>
                                      <AppenderRef ref="logstash" level="trace"/>
                                  </Root>
                              </Loggers>
                          </Configuration>'
configuration-properties:
  comments-service:
    enabled: true